apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: ecom-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: ecom-web
        tier: frontend
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: ecom-web
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.php
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /index.php
            port: 80
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        - secretRef:
            name: {{ .Values.secret.name }}

