apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: ecom-web
        tier: frontend
    spec:
      containers:
      - image: prince450/ecom-web:v3
        name: ecom-web
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.php
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /index.php
            port: 80
        resources:
          requests:
            cpu: "300m"
        env:
        - name: DB_HOST
          value: "mariadb-service"
        - name: DB_USER
          value: "ecomuser"
        - name: DB_PASSWORD
          value: "ecompassword"
        - name: DB_NAME
          value: "ecomdb"

