name: Build and Deploy
on:
  push:
    paths:
      - 'learning-app-ecommerce/**'
      - 'learning-app-ecommerce/**/*'

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: prince450/ecom-web
  HELM_CHART_NAME: ecommerce
  HELM_CHART_VERSION: 0.1.0
  HELM_CHART_PATH: helm-chart-folder/ecommerce

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install yq
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -O /usr/local/bin/yq
        chmod +x /usr/local/bin/yq

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Generate incremental version
      id: version
      run: |
        if [ -f version.txt ]; then
          CURRENT_VERSION=$(cat version.txt)
        else
          CURRENT_VERSION=3
          echo $CURRENT_VERSION > version.txt
        fi
        
        NEW_VERSION=$((CURRENT_VERSION + 1))
        echo $NEW_VERSION > version.txt
        echo "VERSION=v${NEW_VERSION}" >> $GITHUB_OUTPUT
        
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add version.txt
        git commit -m "Bump version to v${NEW_VERSION}"
        git push

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./learning-app-ecommerce
        file: ./learning-app-ecommerce/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.VERSION }}
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.8.0'

    - name: Update Helm chart values
      working-directory: ${{ env.HELM_CHART_PATH }}
      run: |
        # Verify values.yaml exists
        if [ ! -f values.yaml ]; then
          echo "Error: values.yaml not found in ${{ env.HELM_CHART_PATH }}"
          exit 1
        fi
        
        # Update the image tag in values.yaml
        yq e '.image.tag = "${{ steps.version.outputs.VERSION }}"' -i values.yaml
        
        # Verify the change
        cat values.yaml

    - name: Package Helm chart
      working-directory: ${{ env.HELM_CHART_PATH }}
      run: |
        helm package .
        ls *.tgz  # List packaged charts to verify

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload Helm chart to S3
      working-directory: ${{ env.HELM_CHART_PATH }}
      run: |
        CHART_FILE=$(ls *.tgz)
        aws s3 cp "$CHART_FILE" s3://helm-bucket557/
        helm repo index .
        aws s3 cp index.yaml s3://helm-bucket557

    - name: Deploy to Kubernetes
      working-directory: ${{ env.HELM_CHART_PATH }}
      run: |
        aws eks get-token --cluster-name eks-cluster > /dev/null
        helm repo add myapp s3://helm-bucket557
        helm repo update
        helm upgrade --install ${HELM_CHART_NAME} myapp/${HELM_CHART_NAME} \
          --set image.tag=${{ steps.version.outputs.VERSION }} \
          --namespace default